# Generated by Django 3.2.7 on 2021-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesAdda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
